name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ github.ref }}
          files: ./Releases/LibraLoan-win-Setup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
